packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    eslint: ^9.35.0
    prettier: ^3.6.2
    typescript: ^5.9.2
    '@types/node': ^22.17.1
    '@pixpilot/dev-config': ^2.1.0
    vitest: ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    'rollup': ^4.46.2
