name: 'Release Workflow'
on:
  push:
    branches:
      - main
      - next

jobs:
  ci:
    name: Run CI Checks
    uses: ./.github/workflows/ci.yml

  build:
    name: Build Packages
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Generate bot app token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RELEASER_ID }}
          private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          registry-url: 'https://registry.npmjs.org'
          build: 'false'

      - name: Release
        uses: pixpilot/changesets-autopilot@v1
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
